import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Layout/Navbar/Navbar";
import "./globals.scss";
import { Toaster } from "sonner";
import TanstackProvider from "@/components/Providers/TanstackProvider";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DAISY BEAUTY | CHĂM SÓC DA VÀ LÀM ĐẸP CHUẨN Y KHOA",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: 0,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <Navbar />
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster position="top-center" richColors duration={1500} />
        <div className="relative z-0">
          <div className="fixed daisy-background daisy-background-a top-0 right-0"></div>
          <div className="fixed daisy-background daisy-background-b bottom-0 left-0"></div>
        </div>
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-X1R321DMMB" />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
  
            gtag('config', 'G-X1R321DMMB');
          `}
        </Script>
      </body>
    </html>
  );
}
